modLoader = "javafml"
loaderVersion = "[1,)"
license = "GPL-3.0"
issueTrackerURL = "https://github.com/Calemi/Playing-Cards/issues"

[[mods]]
modId = "playingcards"
version = "2.0.0"
displayName = "Playing Cards"
authors = "Calemi, OmbreMoon"
description = '''
Adds playing cards, poker chips, and more!
'''

[[dependencies.playingcards]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.213,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.playingcards]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"
